services:
  mysql:
    image: mysql:8.4
    container_name: kata-pokemon-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kata_pokemon_bot
      MYSQL_USER: kata_user
      MYSQL_PASSWORD: kata_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:4
    container_name: kata-pokemon-adminer
    restart: unless-stopped
    ports:
      - "8090:8080"

volumes:
  mysql_data:
